[package]
name = "pipi"
version = "0.1.0"
authors = ["hangsiahong <honghangsia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.20"
cmd_lib = "1.0.13"
clap = "2.33.3"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
anyhow = "1.0.40"
run_script = "0.8.0"
nix = "*"
